name: learn-github-actions
on:
    push:
        branches: [testing]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: touch 11111111.js          
      - run: npm install -g bats
      - run: npm install dayjs
      - run: bats -v
      - run: ls
      - run: cat package.json
  build-static-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: touch 222222.js
      - run: npm install
      - run: npm run build
      - run: ls
      - run: bats -v
      - run: cat package.json
